### PR TITLE
 MAINT: Updating HiGHS to match latest -- II

### PR DESCRIPTION
**Pull request by HaoZeke**
Cleaner variant of #67 with upstream at https://github.com/ERGO-Code/HiGHS/pull/1987

Necessary for https://github.com/scipy/scipy/pull/21565

### CODE REVIEW

**Comment by HaoZeke** [comment]
OK this needs to be on a different branch to fix the merge conflict, but it is essentially the same as the upstream PR.

**Comment by HaoZeke** [comment]
OK so what should be done here is a force push on `scipy:main` from the final commit of this PR, since otherwise the divergence between (working) upstream and this fork are growing. For now I'll make a new branch and handle the merge conflict there.

**Comment by rgommers** [comment]
> OK so what should be done here is a force push on scipy:main from the final commit of this PR, since otherwise the divergence between (working) upstream and this fork are growing. For now I'll make a new branch and handle the merge conflict there.

That's a little dangerous, since we can't lose the current content on `main` or old versions of SciPy won't be able to find the right commit on checkout. It may be possible to keep the current content in `main` in a separate branch. But a merge between this branch and `main` seems a lot safer.

**Comment by HaoZeke** [comment]
> > OK so what should be done here is a force push on scipy:main from the final commit of this PR, since otherwise the divergence between (working) upstream and this fork are growing. For now I'll make a new branch and handle the merge conflict there.
> 
> That's a little dangerous, since we can't lose the current content on `main` or old versions of SciPy won't be able to find the right commit on checkout. It may be possible to keep the current content in `main` in a separate branch. But a merge between this branch and `main` seems a lot safer.

Makes sense, it also seems like we might need to vendor the `meson` files only in the fork (see https://github.com/scipy/scipy/pull/21565#issuecomment-2425407432 and https://github.com/ERGO-Code/HiGHS/pull/1987#pullrequestreview-2380668057), so then divergences are always going to be present..

**Comment by HaoZeke** [comment]
Closing in favor of the merge based #69.

**Pull request closed without merging**
